
version: '3.8'
services:
  elasticsearch:
    container_name: data-mind-demo-es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    environment:
      - node.name=data-mind-demo-es
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.1
    container_name: data-mind-demo-kibana
    environment:
      ELASTICSEARCH_URL: http://data-mind-demo-es:9200
      ELASTICSEARCH_HOSTS: http://data-mind-demo-es:9200
    ports:
      - 5601:5601
    networks:
      - elastic
  

volumes:
  es-data:
    driver: local

networks:
  elastic:
    driver: bridge
